### PR TITLE
Use custom code for managing history and scroll position

### LINKED ISSUE #3: Generated link wrong when base pathname set
(Reported by @zugarzeeker)

### PR DESCRIPTION
**Pull request by dtinth**
Fixes #3, #4

### CODE REVIEW

File: src/createRenderer.js [hunk 1]
```diff
@@ -73,37 +78,77 @@ export function createRenderer (pages, options = { }) {
...
     legendaryPancake: React.PropTypes.object
   }
 
-  // -- Loads the page and give the content to the manager, and fire callback.
-  function handlePathname (pathname, callback) {
-    currentPathname = pathname
+  function handlePathname (pathname, onFinish) {
     const nextPage = resolvePage(pages, pathname)
+    if (typeof nextPage === 'string') {
+      window.history.replaceState(null, null, rebasePathname(nextPage))
```
Comment (dtinth) [inline src/createRenderer.js:110]: Graceful?

File: src/createRenderer.js [hunk 2]
```diff
@@ -73,37 +78,77 @@ export function createRenderer (pages, options = { }) {
...
     }
+    onLocationChange({ pathname })
   }
 
+  let previousRestorationId = null
+  function loadPageFromLocation (onFinish) {
+    const restorationId = (() => {
+      if (!window.history.state) {
+        const newId = generateNewRestorationId()
+        window.history.replaceState({ restorationId: newId }, null, window.location.href)
```
Comment (dtinth) [inline src/createRenderer.js]: Graceful????

File: src/Link.js [hunk 3]
```diff
@@ -0,0 +1,62 @@
+import classNames from 'classnames'
+import React from 'react'
+
+import { rebasePathname } from './PathUtils'
+
+// # Link {#Link}
```
Comment (dtinth) [inline src/Link.js:5]: Documentation!!!!!!!!
